In [54]:
print("19881A05E3 Mahesh Gupta CSE-C")
import pandas as pd
import numpy as np

19881A05E3 Mahesh Gupta CSE-C


In [13]:
print("________Answer 1__________")

________Answer 1__________


In [3]:
dataf=pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]} )

In [4]:
print(dataf)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [5]:
print("________Answer 2__________")

________Answer 2__________


In [6]:
datadic=exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}


In [7]:
lab = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [8]:
dataf2=pd.DataFrame(datadic,index=lab)


In [9]:
print(dataf2)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [10]:
print("________Answer 3__________")

________Answer 3__________


In [12]:
print(dataf2[['name','score']])


        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [14]:
print("________Answer 4__________")

________Answer 4__________


In [15]:
interval=pd.DataFrame({"X":[1,2,3,4,5,6]},
index=pd.IntervalIndex.from_breaks([1,2,3,4,5,6,7]))


In [16]:
print(interval)

        X
(1, 2]  1
(2, 3]  2
(3, 4]  3
(4, 5]  4
(5, 6]  5
(6, 7]  6


In [17]:
print(interval.index)

IntervalIndex([(1, 2], (2, 3], (3, 4], (4, 5], (5, 6], (6, 7]],
              closed='right',
              dtype='interval[int64]')


In [19]:
interval=pd.DataFrame({"X":[1,2,3,4,5,6]},
index=pd.IntervalIndex.from_tuples([(1,2),(2,3),(3,4),(4,5),(5,6),(6,7)]))

In [20]:
print(interval)

        X
(1, 2]  1
(2, 3]  2
(3, 4]  3
(4, 5]  4
(5, 6]  5
(6, 7]  6


In [21]:
print(interval.index)

IntervalIndex([(1, 2], (2, 3], (3, 4], (4, 5], (5, 6], (6, 7]],
              closed='right',
              dtype='interval[int64]')


In [24]:
interval=pd.DataFrame({"X":[1,2,3,4,5,6]},
index=pd.IntervalIndex.from_arrays([1,2,3,4,5,6],[2,3,4,5,6,7]))

In [25]:
print(interval)
print(interval.index)

        X
(1, 2]  1
(2, 3]  2
(3, 4]  3
(4, 5]  4
(5, 6]  5
(6, 7]  6
IntervalIndex([(1, 2], (2, 3], (3, 4], (4, 5], (5, 6], (6, 7]],
              closed='right',
              dtype='interval[int64]')


In [26]:
data=pd.read_csv('data.csv')

In [27]:
print("_________Answer 5__________")

_________Answer 5__________


In [28]:
print(data.shape)

(5, 5)


In [29]:
print(data.shape[0],data.shape[1])

5 5


In [30]:
print("columns\n",data.columns)

columns
 Index(['Year', 'WHO region', 'Country', 'Beverage Types', 'Display Value'], dtype='object')


In [31]:
print(data)


   Year       WHO region                Country Beverage Types  Display Value
0  1986  Western Pacific               Viet Nam           Wine           0.00
1  1986         Americas                Uruguay          Other           0.50
2  1985           Africa           Cte d'Ivoire           Wine           1.62
3  1986         Americas               Colombia           Beer           4.27
4  1987         Americas  Saint Kitts and Nevis           Beer           1.98


In [39]:
print("________Answer 6______")
arr1=pd.Series([2, 4, 6, 8, 10] )

________Answer 6______


In [33]:
arr2=pd.Series([1, 3, 5, 7, 10] )

In [34]:
print(arr1==arr2)

0    False
1    False
2    False
3    False
4     True
dtype: bool


In [35]:
print(arr1>arr2)

0     True
1     True
2     True
3     True
4    False
dtype: bool


In [36]:
print(arr1<arr2)

0    False
1    False
2    False
3    False
4    False
dtype: bool


In [40]:
print("________Answer 7______")

________Answer 7______


In [41]:
student1 = pd.DataFrame({
        'sid': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'], 
        'marks': [200, 210, 190, 222, 199]})

student2 = pd.DataFrame({
        'sid': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'], 
        'marks': [201, 200, 198, 219, 201]})

In [42]:
mergeddata=pd.concat([student1,student2])

In [43]:
print(mergeddata)

  sid              name  marks
0  S1  Danniella Fenton    200
1  S2      Ryder Storey    210
2  S3      Bryce Jensen    190
3  S4         Ed Bernal    222
4  S5       Kwame Morin    199
0  S4  Scarlette Fisher    201
1  S5  Carla Williamson    200
2  S6       Dante Morse    198
3  S7    Kaiser William    219
4  S8   Madeeha Preston    201


In [44]:
print("________Answer 8_________")

________Answer 8_________


In [45]:
l=[1,2,3,4,5]
nplist=np.array(l)

In [46]:
print(l,nplist)

[1, 2, 3, 4, 5] [1 2 3 4 5]


In [47]:
print("________Answer 9_________")

________Answer 9_________


In [49]:
rang=np.arange(2,11).reshape(3,3)

In [50]:
print(rang)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [51]:
print("________Answer 10_________")

________Answer 10_________


In [52]:
randarray=np.random.random((3,3,3))

In [53]:
print(randarray)

[[[0.42451243 0.52000754 0.6220393 ]
  [0.95290798 0.21807934 0.5335346 ]
  [0.43466595 0.67037861 0.30249534]]

 [[0.25552446 0.97820314 0.93063299]
  [0.80930071 0.19940209 0.85373292]
  [0.82248626 0.41144767 0.7900232 ]]

 [[0.23246068 0.37083784 0.32627462]
  [0.07700135 0.17068354 0.71146175]
  [0.60574654 0.69279231 0.75138252]]]
